sudo: false

language: node_js

node_js:
  - "node"

before_script:
  - npm uninstall typescript --no-save
  - npm uninstall tslint --no-save
  - npm run setup
  - npm run build

script:
  - npm run lint
  - npm run coverage

after_success:
  - npm run coveralls
  - npm run typedoc
  - npm pack

deploy:
  - provider: pages
    skip_cleanup: true
    local_dir: docs/
    github_token: $GITHUB_TOKEN
    on:
      branch: master
      tags: true
  - provider: releases
    api_key: $GITHUB_TOKEN
    file_glob: true
    file: "ts-scikit-*.tgz"
    skip_cleanup: true
    on:
      branch: master
      tags: true
  - provider: npm
    skip_cleanup: true
    email: "chris.engelsma@gmail.com"
    api_key: $NPM_TOKEN
    on:
      branch: master
      tags: true
